name: Live Betting Test Feedback
description: Report your experience and findings from live betting testing
title: "[Live Betting Test]: "
labels: ["live betting test", "review"]
assignees:
  - team_member_username
body:
  - type: markdown
    attributes:
      value: |
        Thank you for participating in our Live Betting testing on the Polygon Mumbai testnet. Please fill out the following details to help us track and improve our system.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you for additional information?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: wallet-address
    attributes:
      label: Your Wallet Address
      description: Where would you like to get your reward?
      placeholder: 0xe3h...
    validations:
      required: true

  - type: dropdown
    id: test-type
    attributes:
      label: Testing Scenario Conducted
      description: Select the testing scenario you conducted.
      options:
        - Cheat Bet
        - Odds Comparison
        - Arbitrage Strategy
        - System Flaw Exploration
        - Bug Patterns
    validations:
      required: true

  - type: textarea
    id: test-description
    attributes:
      label: Test Description
      description: Describe the specific test scenario you conducted (e.g., aftergoal bet, odds discrepancy test).
      placeholder: Describe the test scenario...
    validations:
      required: true

  - type: textarea
    id: observed-behavior
    attributes:
      label: Observed Behavior
      description: Describe the behavior you observed as a result of the test.
      placeholder: What happened during and after the test?
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen during the test.
      placeholder: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: reproducibility
    attributes:
      label: Reproducibility of the Issue
      description: Describe if and how the issue can be reproduced.
      placeholder: Steps to reproduce the issue...
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any other relevant information or context about the test.
      placeholder: Any other details...

